[package]
name = "ui_macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish.workspace = true

[lib]
path = "src/ui_macros.rs"
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true

[dev-dependencies]
component.workspace = true
ui.workspace = true

[lints]
workspace = true
